version: 2

sources:
  - name: raw_data
    description: "Raw data from Intervals ICU activities"
    database: ethereal-bison-491017-d8
    schema: athlete_training_dataset
    tables:
      - name: activities
        description: "Raw activities loaded from Intervals.icu via dlt"
        columns:
          - name: _id
            data_tests:
              - unique
              - not_null

models:
  - name: stg_activities
    description: "Cleaned and typed activities from Intervals.icu"
    columns:
      - name: activity_id
        data_tests:
          - unique
          - not_null
      - name: athlete_id
        data_tests:
          - not_null
      - name: activity_type
        data_tests:
          - not_null
      - name: start_date_local
        data_tests:
          - not_null
      - name: moving_time_sec
        data_tests:
          - not_null